spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3006/productivitydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:Sunshine@84}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: ProductivityAppPool
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      minimum-idle: 5
      maximum-pool-size: 20
      leak-detection-threshold: 60000
      connection-test-query: SELECT 1
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  thymeleaf:
    cache: true
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  messages:
    basename: i18n/messages
  resources:
    add-mappings: true
    cache:
      period: 1h
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:changeit}

server:
  port: 8080
  address: 0.0.0.0
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  servlet:
    context-path: /

# Logging
logging:
  level:
    root: INFO
    org.springframework: WARN
    com.yourapp: DEBUG
  file:
    name: logs/application.log
    max-size: 10MB
    max-history: 7
    total-size-cap: 100MB
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Application specific properties
app:
  name: Productivity Dashboard
  version: 1.0.0
  security:
    jwt:
      secret: your-secret-key-here
      expiration: 86400000  # 24 hours in milliseconds

# Telegram Bot Configuration
telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:your-telegram-bot-token}
    username: ${TELEGRAM_BOT_USERNAME:your_bot_username}
    chat-id: ${TELEGRAM_CHAT_ID:your_chat_id}
    enabled: ${TELEGRAM_ENABLED:false}  # Set to true to enable Telegram notifications
