spring:
  datasource:
    url: jdbc:mysql://localhost:3006/productivitydb
    username: root
    password: Sunshine@84
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
server:
  port: 8080
telegram:
  bot-token: 7638552289:AAG9I5sQCss-VWMq16NjHCGE5vkVTt5VkRc
  chat-id: 8259425689

# Sleep window (24h format)
sleep:
  start: "23:00"  # 11 PM
  end:   "06:00"  # 6 AM
