spring:
  profiles:
    active: @spring.profiles.active@
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  
  thymeleaf:
    cache: false
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

# Common application properties
app:
  name: Productivity Dashboard
  version: 1.0.0

# Development server settings (overridden in application-prod.yml for production)
server:
  port: 8080

# Application properties
admin:
  username: ${ADMIN_USERNAME:admin}
  password: ${ADMIN_PASSWORD:changeit}

# Sleep window (24h format)
sleep:
  start: "23:00"  # 11 PM
  end:   "06:00"  # 6 AM

# Logging
logging:
  level:
    root: INFO
    com.yourapp: DEBUG
  file:
    name: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
